// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy. If needed, add more secrets to the .env file at the project root. (Excluded from git/source control)
// This file should not be committed with actual instrumentation key!
export const environment = {
  production: true,
  APPINSIGHTSINSTRUMENTATIONKEY: 'TEST',
};
