/* tslint:disable */
// @ts-nocheck
const path = require('path');
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

console.log('Current working directory:', process.cwd());
require('dotenv').config({
  path: path.join(process.env.GITHUB_WORKSPACE ?? '.', '.env'),
});

const environment = argv.environment;
if (!process.env.APPINSIGHTSINSTRUMENTATIONKEY) {
  console.error('Error: APPINSIGHTSINSTRUMENTATIONKEY is not set');
  process.exit(1);
}

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');

// Checks whether command line argument of `prod` was provided signifying production mode
const isProduction = environment === 'prod';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy. If needed, add more secrets to the .env file at the project root. (Excluded from git/source control)
  export const environment = {
    production: ${isProduction},
    APPINSIGHTSINSTRUMENTATIONKEY: '${process.env.APPINSIGHTSINSTRUMENTATIONKEY}'
  };
`;
console.log('Wrote the following environment file: ', environmentFileContent);

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* tslint:enable */
